### ISSUE TITLE
conda installation failure

### ISSUE THREAD

**Issue by lokeshwer** [DeployQL/LintDB#22]
`conda install lintdb -c deployql -c conda-forge`

Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 187, in conda_http_errors
        yield
      File "/home/user/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 153, in repodata
        response.raise_for_status()
      File "/home/user/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/deployql/linux-64/current_repodata.json
    
    During handling of the above exception, another exception occurred:

**Comment by mtbarta** [comment]
What OS and what version of Python are you using? LintDB has built packages for 3.9-3.12 for OSX and Linux.

The error suggests you can't find the channel. I double checked that it's public. 

Based on [this SO post](https://stackoverflow.com/questions/61134985/conda-install-packages-error-collecting-package-metadata-current-repodata-json), this might be solved by regenerated the .condarc file.

Are you behind a proxy?

**Comment by mtbarta** [comment]
closing as stale. Let me know if you've solved the issue.
